// Shared unit-of-measurement options for product weight/quantity dropdowns.
export const UNIT_GROUPS = [
  {
    label: 'Weight',
    options: [
      { value: 'kg', label: 'Kilogram (kg)' },
      { value: 'g', label: 'Gram (g)' },
      { value: 'mg', label: 'Milligram (mg)' },
      { value: 'q', label: 'Quintal (q)' },
      { value: 't', label: 'Metric Ton (t)' },
      { value: 'lb', label: 'Pound (lb)' },
      { value: 'oz', label: 'Ounce (oz)' },
    ],
  },
  {
    label: 'Volume',
    options: [
      { value: 'l', label: 'Liter (L)' },
      { value: 'ml', label: 'Milliliter (mL)' },
      { value: 'm3', label: 'Cubic Meter (m³)' },
      { value: 'cc', label: 'Cubic Centimeter (cc)' },
    ],
  },
  {
    label: 'Length',
    options: [
      { value: 'mm', label: 'Millimeter (mm)' },
      { value: 'cm', label: 'Centimeter (cm)' },
      { value: 'm', label: 'Meter (m)' },
      { value: 'km', label: 'Kilometer (km)' },
      { value: 'in', label: 'Inch (in)' },
      { value: 'ft', label: 'Foot (ft)' },
      { value: 'yd', label: 'Yard (yd)' },
    ],
  },
  {
    label: 'Area',
    options: [
      { value: 'sqm', label: 'Square Meter (m²)' },
      { value: 'sqft', label: 'Square Foot (ft²)' },
      { value: 'acre', label: 'Acre' },
      { value: 'hectare', label: 'Hectare' },
    ],
  },
  {
    label: 'Quantity',
    options: [
      { value: 'pcs', label: 'Piece (pcs)' },
      { value: 'unit', label: 'Unit (unit)' },
      { value: 'nos', label: 'Number (nos)' },
      { value: 'pair', label: 'Pair' },
      { value: 'set', label: 'Set' },
      { value: 'box', label: 'Box' },
      { value: 'pack', label: 'Pack' },
      { value: 'packet', label: 'Packet' },
      { value: 'carton', label: 'Carton' },
      { value: 'bundle', label: 'Bundle' },
      { value: 'roll', label: 'Roll' },
      { value: 'bag', label: 'Bag' },
      { value: 'bottle', label: 'Bottle' },
      { value: 'can', label: 'Can' },
      { value: 'jar', label: 'Jar' },
      { value: 'tube', label: 'Tube' },
      { value: 'tin', label: 'Tin' },
      { value: 'sachet', label: 'Sachet' },
      { value: 'strip', label: 'Strip' },
      { value: 'tray', label: 'Tray' },
      { value: 'crate', label: 'Crate' },
      { value: 'case', label: 'Case' },
      { value: 'dozen', label: 'Dozen' },
      { value: 'half-dozen', label: 'Half Dozen' },
      { value: 'gross', label: 'Gross' },
    ],
  },
  {
    label: 'Food & Restaurant',
    options: [
      { value: 'plate', label: 'Plate' },
      { value: 'bowl', label: 'Bowl' },
      { value: 'cup', label: 'Cup' },
      { value: 'glass', label: 'Glass' },
      { value: 'spoon', label: 'Spoon' },
      { value: 'tsp', label: 'Teaspoon (tsp)' },
      { value: 'tbsp', label: 'Tablespoon (tbsp)' },
      { value: 'slice', label: 'Slice' },
      { value: 'loaf', label: 'Loaf' },
      { value: 'portion', label: 'Portion' },
      { value: 'serving', label: 'Serving' },
    ],
  },
  {
    label: 'Liquid Containers',
    options: [
      { value: 'drum', label: 'Drum' },
      { value: 'barrel', label: 'Barrel' },
      { value: 'tank', label: 'Tank' },
    ],
  },
  {
    label: 'Agriculture',
    options: [
      { value: 'seed', label: 'Seed' },
      { value: 'plant', label: 'Plant' },
      { value: 'bunch', label: 'Bunch' },
      { value: 'bale', label: 'Bale' },
    ],
  },
];
